language: php

php:
  - 7.0

sudo: false

install:
  - composer global require hirak/prestissimo --prefer-dist --no-interaction --no-progress
  - travis_retry composer install --prefer-dist --no-interaction --no-progress

script: composer test
