language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_install:
  - composer self-update
  - composer global require hirak/prestissimo --prefer-dist --no-interaction --no-progress

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-progress

script:
  - composer test

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "5.5.9" ]; then vendor/bin/phpunit --coverage-clover build/clover.xml --whitelist src; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "5.5.9" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "5.5.9" ]; then php ocular.phar code-coverage:upload --format=php-clover build/clover.xml; fi;
