language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_install:
  - composer self-update
  - composer global require hirak/prestissimo --prefer-dist --no-interaction --no-progress

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-progress

script:
  - composer test
